"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from decouple import config
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-483rh0c#q0^5-r187=n8mcews#@qk3cn2@nmd6@w)m9q&scto$'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # created apps
    'apps.accounts',
    'apps.common',
    'apps.locations',
    'apps.merchants',
    'apps.catalog',
    'apps.carts',
    'apps.orders',
    'apps.couriers',
    'apps.dispatch',
    'apps.payments',
    'apps.promotions',
    'apps.notifications',
    'apps.reviews',
    'apps.support',

    # third-party apps
    'rest_framework',
    'rest_framework_simplejwt',
    'django_celery_beat',
    "channels",


]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
AUTH_USER_MODEL = "accounts.User"


# CELERY BEAT SCHEDULE
from celery.schedules import crontab

CELERY_BROKER_URL = "redis://localhost:6379/0"
CELERY_RESULT_BACKEND = "redis://localhost:6379/1"
CELERY_TIMEZONE = "Asia/Tashkent"
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_BEAT_SCHEDULER = "django_celery_beat.schedulers:DatabaseScheduler"


# CELERY_BEAT_SCHEDULE = {
#     "auto-cancel-unpaid-orders": {
#         "task": "apps.orders.tasks.auto_cancel_unpaid_orders",
#         "schedule": crontab(minute="*/5"),  # har 5 daqiqada
#     },
#     "cleanup-stale-carts": {
#         "task": "apps.orders.tasks.cleanup_stale_carts",
#         "schedule": crontab(minute=0, hour="*/2"),  # har 2 soatda
#     },
# }

CELERY_BEAT_SCHEDULE = {
    # Dispatch
    "sweep-expired-offers": {
        "task": "apps.dispatch.tasks.sweep_expired_offers",
        "schedule": 60.0,  # har 60 soniyada
    },
    # Orders
    "auto-cancel-unpaid-orders": {
        "task": "apps.orders.tasks.auto_cancel_unpaid_orders",
        "schedule": crontab(minute="*/5"),
    },
    "cleanup-stale-carts": {
        "task": "apps.orders.tasks.cleanup_stale_carts",
        "schedule": crontab(minute=0, hour="*/2"),
    },
    # Couriers
    "cleanup-old-location-pings": {
        "task": "apps.couriers.tasks.cleanup_old_location_pings",
        "schedule": crontab(minute=0, hour=2),  # kecha soat 02:00
    },
    "auto-end-stale-shifts": {
        "task": "apps.couriers.tasks.auto_end_stale_shifts",
        "schedule": crontab(minute=0),  # har soatda
    },
}
ASGI_APPLICATION = "config.asgi.application"
CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels_redis.core.RedisChannelLayer",
            "CONFIG": {"hosts": [("127.0.0.1", 6379)]},
        }
    }

# FCM
FCM_SERVER_KEY = config("FCM_SERVER_KEY")

# SMS (choose one)
SMS_PROVIDER = "eskiz"  # or "playmobile"
ESKIZ_EMAIL = config("ESKIZ_EMAIL")
ESKIZ_PASSWORD = config("ESKIZ_PASSWORD")
ESKIZ_FROM = "4546"  # or your sender name

# Telegram admin alerts
TELEGRAM_BOT_TOKEN = config("TELEGRAM_BOT_TOKEN")
TELEGRAM_ADMIN_CHAT_ID = config("TELEGRAM_ADMIN_CHAT_ID")

# Email
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
DEFAULT_FROM_EMAIL = "noreply@glovo.uz"

TELEGRAM_BOT_TOKEN = config("TELEGRAM_BOT_TOKEN")
TELEGRAM_BOT_USERNAME = config("TELEGRAM_BOT_USERNAME")   # @ belgisisiz, masalan: "GlovoUZBot"
TELEGRAM_WEBHOOK_SECRET = config("TELEGRAM_WEBHOOK_SECRET")